### ISSUE TITLE
-stride option and its affects

### ISSUE THREAD

**Issue by IBman1** [PawelGorny/WifSolverCuda#5]
i,m trying to understand the option -stride and its affects:
1. is 58^8 the min and is 58^50 the max ? can the value be 0 or 1?
2.  what if i lost say 10 chars or 11 chars from the end what value i shoud  use for -stride, in this case i can not count for 58^8?
3.  can we say that with -stride , we are trying to skip unneeded calculation so we reach faster. this is important to explain so the user can understand its value and function.

**Comment by PawelGorny** [comment]
WIF is a form of encoding given longer hex value. It contains network flag, private key itself, compression flag (for compressed keys) and checksum.
If we decode WIF, it produces given private key. If we want to find the next possible WIF we must change one of characters. Now, if you change character at the very end, it modifies decoded value by 1. Second from right 58^1 = 58. Third = 58^2 = 3364 etc.
I pre-calculated strides because many users do not know how to do it and which value use.
So, if you have missing character at a given position, we must know how we should increment "decoded" content to have the same value like WIF with changed letter. Just adding number is faster than replacing letter and decoding.
I am not sure if I explain clear enough...
BUT - the program is intended to be used when decoded checksum is known. Algorithm is based on fact that I very quickly verify it generated checksum is equal to expected one, then I check if private key generates correct address. It is big improvement comparing to brute-force method (like in BitCrack) where every private key is converted to address and checked (it is more time consuming).
So, if in your case you have missing the whole end it cannot be used... Or contact me on email to discuss if we may find other way to solve it.  10-11 missing from the end is easily solvable, I may help you with that.
If you have missing beginning or middle (end - with checksum - is decodable), WifSolveCuda may be used, if the whole end is missing - not today.

**Comment by kpot87** [comment]
Hi @PawelGorny  and good question from @IBman1 . @PawelGorny ok than how this decoded?
WifSolverCuda.exe -stride 7479027ea100 -c -rangeStart 8070cfa0d40309798a5bd144a396478b5b5ae3305b7413601b18767654f1108a02787692623a  -a 1PzaLTZS3J3HqGfsa8Z2jfkCT1QpSMVunD

here’s no checksum

**Comment by PawelGorny** [comment]
-decode WIF
It only displays decoded WIF, there are no calculations. It is just a helper

Please check docs/examples, to see how to construct parameters.
Checksum is always 8 last decoded characters.
If stride is small (last 8 characters are != 00000000), then stride affects checksum and you launch program only using rangeStart/stride
If stride is large (last 8 characters = '00000000), which means it is 58^40 and bigger, then you may add additional parameter -checksum [8 last characters]. It is not necessary because still program will check if given key produces good checksum, but it makes program slightly faster. Just a bit. A little ;-)

**Comment by kpot87** [comment]
> -decode WIF It only displays decoded WIF, there are no calculations. It is just a helper
> 
> Please check docs/examples, to see how to construct parameters. Checksum is always 8 last decoded characters. If stride is small (last 8 characters are != 00000000), then stride affects checksum and you launch program only using rangeStart/stride If stride is large (last 8 characters = '00000000), which means it is 58^40 and bigger, then you may add additional parameter -checksum [8 last characters]. It is not necessary because still program will check if given key produces good checksum, but it makes program slightly faster. Just a bit. A little ;-)

Ok, for my understanding ) 

KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qYw6srz7bjJae1CAUm31 

KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qYw6srz???????CAUm31 check sum from wif is CAUm31 or e1CAUm31?
