### ISSUE TITLE
kernel launch failed: ###

### ISSUE THREAD

**Issue by giobesia** [PawelGorny/WifSolverCuda#6]
Hello Sir, im trying to run latest release version but get that message, kernel launch failed: ###.
im currently using older CUDA, thats GTX 1050 TI.
Can you please, teach me how to rebuild this for windows 10 x64 ?
i'm just new for C proggramming.
Thank you !!

**Comment by PawelGorny** [comment]
I you just want to launch, please to try "WifSolverCuda_102_ccap54.exe" from release 4.4 (https://github.com/PawelGorny/WifSolverCuda/releases/tag/0.4.4)

Otherwise, you must need Visual Studio (I used version 2019) and NVIDIA CUDA toolkit, then in project file replace all references to version 11.6 by your version of CUDA (for example 10.2). You will also need to change compute capability to the one which is correct for your card (https://developer.nvidia.com/cuda-gpus)
For 1050 it will be 61.

**Comment by giobesia** [comment]
Thank you very much for replying sir,
I have trying that version you suggest and it's work great now.
Thank You sir.
